# Generated by Django 3.1.2 on 2020-10-23 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_todo_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='datecompleted',
        ),
    ]
