# Generated by Django 3.1.2 on 2020-10-23 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_todo_datecompleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='todo',
        ),
    ]
