# Generated by Django 3.1.2 on 2020-10-23 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='importent',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
