# Generated by Django 3.1.2 on 2020-10-23 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20201022_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='datecompleted',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='importent',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
