# Generated by Django 3.1.2 on 2020-10-24 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_auto_20201024_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
