# Generated by Django 3.1.2 on 2020-10-24 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_todo_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='datecompleted',
            new_name='date_completed',
        ),
    ]
